apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-environments
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thebottlerocket/argo-example/
    targetRevision: HEAD
    path: 
  destination:
    server: https://kubernetes.default.svc
    namespace: test-env
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHead: true
      prune: true
