apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-environments
spec:
  selector:
    matchLabels:
      app: test-environments
  template:
    metadata:
      labels:
        app: test-environments
    spec:
      containers:
      - name: myapp
        image: it-builds.repos.natinst.com/argocd/test-environments:0.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
